sudo: required

language: java

jdk:
  - openjdk8

spring :
  logging :
    level :
      org.springframework.*: OFF
      guru.springframework.*: OFF
      org.hibernate: OFF

logging.level.root=OFF 

script:
  - mvn test -q -B