sudo: required

language: java

jdk:
  - openjdk8

env:
DOCKER_COMPOSE_VERSION: 1.24.0

services:
  - docker

script:
  #- docker-compose up -d
  - echo "ON LANCE 100 PARTIES"
  - docker-compose scale serveur=1 joueur=50 joueur2=50
  - docker-compose logs
  - docker-compose ps
