sudo: required

language: java

jdk:
  - openjdk8

env:
DOCKER_COMPOSE_VERSION: 1.24.0

services:
  - docker

script:
  - cd serveur && docker build -f Dockerfile -t serveur .
  - cd ../joueur && docker build -f Dockerfile -t joueur .
  #- docker-compose up -d
  - echo "ON LANCE 100 PARTIES"
  - docker-compose scale serveur=1 joueur=10
  - docker-compose logs
  - docker-compose ps
  #- echo " LANCEMENT DE TEST DE COMMUNICATION ENTRE JOUEUR ET SERVEUR"
  #- cd ../joueur && mvn clean test #lancer test de connexion  au serveur pour montrer la communication entre les 2 containers