language: java

env:
DOCKER_COMPOSE_VERSION: 1.20.1

services:
- docker

script:
- cd  serveur && docker build -f Dockerfile -t serveur .
- cd ../joueur && docker build -f Dockerfile -t joueur .
- docker-compose up
- docker-compose ps
