sudo: required

language: java

jdk:
  - openjdk8

env:
DOCKER_COMPOSE_VERSION: 1.24.0

services:
  - docker

script:
  - docker-compose up -t 60
  - echo "ON LANCE 100 PARTIES"
  - docker-compose ps
