sudo: required

language: java

jdk:
  - openjdk8

spring :
  logging :
    level :
      org.springframework.*: OFF
      guru.springframework.*: OFF
      org.hibernate: OFF


script:
  - logging.level.root=OFF
  - mvn test -q -B