version: '3'
services:

  serveur:
    image: serveur
    restart: always
    build:
      dockerfile: serveur/Dockerfile
    ports:
    - "8080:8080"


  joueur:
    image: joueur
    restart: always
    build:
      dockerfile: joueur/Dockerfile
    ports:
    - "8081:8081"


