

version: '3.3'
services:

  serveur:
    image: serveur
    restart: always
    ports:
    - "8080:8080"
    networks:
    - network1


  joueur:
    image: joueur
    restart: always
    ports:
    - "8081:8081"
    depends_on:
    - serveur
    networks:
    - network1

networks:
  network1:
