version: "3.3"

services:

  joueur:
    build: joueur/
    command: java -jar joueur-1.0.jar
    restart: always
    depends_on:
     - serveur
    networks:
    - network1
#pour logs en local
#  joueur2:
#    build: joueur/
#    command: java -jar joueur-1.0.jar
#    restart: always
#    depends_on:
#     - serveur
#    networks:
#     - network1

  serveur:
    build: serveur/
    command: java -jar serveur-1.0.jar
    ports:
      - "8080:8080"
    networks:
    - network1

networks:
  network1: